version: '3'

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis

  wiremock:
    image: rodolpheche/wiremock
    build:
      context: .
    command: --port 4000
    hostname: wiremock
    ports:
      - "4000:4000"
    volumes:
      - ./wiremock/stubs:/home/wiremock

volumes:
  postgres:
  redis:

networks:
  docker_dev_tools:
    external: true
