version: '3'

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh

volumes:
  postgres:

networks:
  docker_dev_tools:
    external: true
